### ISSUE TITLE
Troubles with building the library

### ISSUE THREAD

**Issue by PeterLarsen19** [bjarnekvae/pymonarco-hat#1]
Hey 

I am experiencing some issues with building the library file from the Monarco HAT source code, i get this error message from the monarco_crc.o file:

relocation R_ARM_MOVW_ABS_NC against 'a local symbol' can not be used when making a shared object; 

and:

error adding symbols: Bad value

is it something you have experienced before? and could it be that we are not using the same compiler?

Best

**Comment by bjarnekvae** [comment]
Hi!

Can you copy/paste the whole output from the compiler?

I have not seen this before, what hardware are you using? This code is tested and compiled on Raspberry Pi 3 B+ with Raspbian (Lite) installation.

I don't think we are using different compiler as the compiler used is defined in the makefile under the "CC" constant, unless you have changed this.

Can you try to compile the example code from the monarco-hat-driver-c repository and see if you get the same error?

**Comment by PeterLarsen19** [comment]
Hey

Here is the whole out from the compiler:

pi@raspberry: ~ /pymonarco-hat/monarco-c $ make MONARCO_PATH=/home/pi/monarco-hat-driver-c/
/usr/bin/arm-linux-gnueabihf-gcc -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -g -fPIC -c -Wall -Wno-write-strings -fmessage-length=0 -Wno-uninitialized -Werror=uninitialized -Wno-sign-compare -Werror=strict-aliasing -Wno-maybe-uninitialized -Wno-strict-aliasing -I/home/pi/monarco-hat-driver-c// -I/home/pi/monarco-hat-driver-c//platform/linux -c dprint_flags.c -o dprint_flags.o
/usr/bin/arm-linux-gnueabihf-gcc -shared -fPIC -o libmonarco.so  /home/pi/monarco-hat-driver-c//src/monarco_crc.o  /home/pi/monarco-hat-driver-c//src/monarco.o  /home/pi/monarco-hat-driver-c//src/monarco_util.o dprint_flags.o
/usr/bin/ld: /home/pi/monarco-hat-driver-c//src/monarco_crc.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/pi/monarco-hat-driver-c//src/monarco_crc.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'libmonarco.so' failed
make: *** [libmonarco.so] Error 1
pi@raspberry:~/pymonarco-hat/monarco-c $

And here is the gcc
GCC -v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 6.3.0-18+rpi1+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1)

I am using a Raspberry pi 3 B with Raspbian 9.8 stretch (Lite)

**Comment by bjarnekvae** [comment]
Try do do a full clean before you recompile:
make clean MONARCO_PATH=/home/pi/monarco-hat-driver-c/

then recompile with
make MONARCO_PATH=/home/pi/monarco-hat-driver-c/

**Comment by PeterLarsen19** [comment]
Great that did it

Thank you very much
