### ISSUE TITLE
pymonarco-hat/examples

### ISSUE THREAD

**Issue by PavelKomrs** [bjarnekvae/pymonarco-hat#2]
I have dificulty run monarco_example.py
I try run:
import pymonarco_hat as plc
import sys
import time

plc_handler = plc.Monarco('/home/pi/pymonarco-hat/monarco-c/libmonarco.so', debug_flag=plc.MONARCO_DPF_WRITE | plc.MONARCO_DPF_VERB)

plc_handler.set_pwm_frequency(plc.PWM_CHANNEL1, 1000)
plc_handler.set_pwm_out(plc.DOUT2, 0.75)
plc_handler.set_analog_out(plc.AOUT1, 5.0)

while 1:
    plc_handler.set_digital_out(plc.DOUT1, plc.HIGH)
    time.sleep(1)
    plc_handler.set_digital_out(plc.DOUT1, plc.LOW)
    time.sleep(1)

    print("DIN1:", plc_handler.get_digital_in(plc.DIN1))
    print("AIN1:", plc_handler.get_analog_in(plc.AIN1))

and I go this error:
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
============ RESTART: /home/pi/Desktop/monarco/monarco_example.py ============
Traceback (most recent call last):
  File "/home/pi/Desktop/monarco/monarco_example.py", line 6, in <module>
    plc_handler = plc.Monarco('/home/pi/pymonarco-hat/monarco-c/libmonarco.so', debug_flag=plc.MONARCO_DPF_WRITE | plc.MONARCO_DPF_VERB)
  File "/usr/local/lib/python3.5/dist-packages/pymonarco_hat-0.1-py3.5.egg/pymonarco_hat/pymonarco_hat.py", line 136, in __init__
    self.__monarco.monarco_init(ctypes.pointer(self.__cxt), ctypes.c_char_p(spi_interface.encode('utf-8')),
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/pi/pymonarco-hat/monarco-c/libmonarco.so: undefined symbol: monarco_init

**Comment by bjarnekvae** [comment]
Can you post the output when you compiled the libmonarco.so-file?

**Comment by bjarnekvae** [comment]
Is the path correct in the plc.Monarco()-function by the way?

**Comment by PavelKomrs** [comment]
path looks correct I used copy path and when I remove libmonarco.so from file monarco-c I got error message missing file.

I have not original  compiled output of libmonarco.so when I try compiled it again I got message for "for default nothing has done" 
when I remove file I got 
 make MONARCO_PATH=/home/pi/monarco-hat-driver-c
/usr/bin/arm-linux-gnueabihf-gcc -shared -o libmonarco.so  /home/pi/monarco-hat-driver-c/src/monarco_crc.o  /home/pi/monarco-hat-driver-c/src/monarco.o  /home/pi/monarco-hat-driver-c/src/monarco_util.o dprint_flags.o
/usr/bin/ld: /home/pi/monarco-hat-driver-c/src/monarco_crc.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/pi/monarco-hat-driver-c/src/monarco_crc.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:21: nĂˇvod pro cĂ­l â€žlibmonarco.soâ€ś selhal
and file(libmonarco.so) was not created

**Comment by bjarnekvae** [comment]
looks like libmonarco.so is not being compiled properly, try the solution from issue #1:

Try do do a full clean before you recompile:
make clean MONARCO_PATH=/home/pi/monarco-hat-driver-c/

then recompile with
make MONARCO_PATH=/home/pi/monarco-hat-driver-c/

**Comment by PavelKomrs** [comment]
I started from beginning from new raspberrian. now monarco_example.pi  working. root cause was probably wrong path how you mentioned

Can I have second question. 
how I will got value from W1 temperature sensor conected to monarco hat terminal

**Comment by bjarnekvae** [comment]
Good to know everything is working properly.

I need to know more about the temperature sensor to help you. Can you give me the product name?
