### ISSUE TITLE
Problem using library

### ISSUE THREAD

**Issue by ejpaardekam** [bjarnekvae/pymonarco-hat#5]
Hi Bjarne,  

I recently purchased a MonarcoHAT, and I am having some trouble getting it up and running using the Python library you created. Could you help me perhaps? Below is some relevant information: 

- MonarcoHAT (unsure of version, but it was purchased from the manufacturer a week ago) on top of Raspberry Pi model 4B with Python version 3
- 24V DC power supply
- When power is connected, the Raspberry Pi begins to boot. The LED on the MonarcoHAT flashes on/off orange in ~ 0.5 second intervals, and shortly after a green LED lights up. Once the Raspberry Pi has finished booting, all of the LEDs on the MonarcoHAT go off. 
- I followed all of the steps in this guide (https://github.com/bjarnekvae/pymonarco-hat) without issues or errors. I have a wire running from AIN1 to AOUT1. When I run the example listed in the final step, it says "monarco_init: OK", and then simply displays readings of 0.0, when I would expect to see 5 Volts coming out of Analog output 1 on the reading of Analog input 1. Making a small edit to the code which should cause an LED to light up also does not seem to work. I do not seem to be able to program the analog or digital outputs of the MonarcoHAT.

I would highly appreciate any assistance you could provide with this issue. If there is any additional info that would be useful to know, I'm happy to provide it. Thank you in advance for your help.

**Comment by bjarnekvae** [comment]
Hi, 

First of all, did you enable the Raspberry Pi SPI interface? The Raspberry Pi is communicating with the Monarco HAT trough this interface and you can enable/disable the hardware interfaces by typing `sudo raspi-config` in the terminal.

By default you need root access to use the SPI interface on a raspberry pi, here you can try to run the script as root root? E.g:
`sudo python3 monarco_example.py /path/to/lib/libmonarco.so`

If this works and you don't want to run python scripts as root all the time, you can change the access permissions on the SPI interface, see [here](https://roboticsbackend.com/raspberry-pi-hardware-permissions/#Enable_SPI).

Tell me how it goes :)

**Comment by ejpaardekam** [comment]
I did enable the SPI interface before I started, yes. I also enabled SPI1, as I want to use it to read out a sensor, and the MonarcoHAT uses the available I2C channels as well as SPI0. Could it be related to that? Running the example as root did not change the outcome. I will try to revert the change I made to config to see if it changes anything.

**Comment by bjarnekvae** [comment]
Does the orange LED change the blinking frequency when you execute the example code? The LED should blink slower when the example script is running.

Also, change line 6 in the example from this:
`plc_handler = plc.Monarco(lib_path, debug_flag=plc.MONARCO_DPF_WRITE | plc.MONARCO_DPF_VERB)`

to this:
`plc_handler = plc.Monarco(lib_path, debug_flag=plc.MONARCO_DPF_WRITE | plc.MONARCO_DPF_VERB | plc.MONARCO_DPF_ERROR | plc.MONARCO_DPF_WARNING | plc.MONARCO_DPF_INFO | plc.MONARCO_DPF_READ)`

This should print all potential errors during execution

**Comment by ejpaardekam** [comment]
Hi again Bjarne, 

It seems the problem I have is indeed caused by the enabling of SPI1 in config.tx using the command "dtoverlay=spi1-3cs"; removing this line allows the Monarco to run as expected, and the example runs without error. So that is nice. 

However, I still need to be able to read out my sensor (BME680 by Bosch on an Adafruit breakout board) with the Monarco running. Since the Monarco (claims to) reserve I2C channels 0 and 1, and SPI channel 0, I am not left with many options. I hope you don't mind me asking here if you have any recommendations for dealing with this limitation?

**Comment by bjarnekvae** [comment]
The SPI protocol supports multiple devices on the same SPI bus by using CS-pin (Chip Select) to select the device to read/write data to, [here](https://en.wikipedia.org/wiki/Serial_Peripheral_Interface#/media/File:SPI_three_slaves.svg) is a nice drawing illustrating this.

But, if you want to use the same SPI peripheral for multiple devices you must make sure that the processes accessing the SPI peripheral are synchronized, and not trying to access the interface at the same time (this is probably your issue). The pymonarco-HAT code is running a separate [thread](https://github.com/bjarnekvae/pymonarco-hat/blob/912d156efbac9e4490cf22a109b00ecaf3bdfb95/pymonarco_hat/pymonarco_hat.py#L145) when it accesses the SPI interface. You could synchronize the access to the SPI interface by e.g. using a mutex or a queue.

This is just educated guessing, as I don't know everything about your setup.

Good luck :)

**Comment by ejpaardekam** [comment]
A quick update: 

Turns out that due to some ambiguous phrasing in the MonarcoHAT manual, I had incorrectly understood that I could not use additional devices on the default I2C bus. I was able to connect and read out my sensor with I2C on the default bus, and now things appear to be working as expected. Thanks again for your input!
